export interface AlgorithmInfo {
    name: string;
    description: string;
    complexity: string;
    code: string[];
    eventLineMap: Record<string, number[]>;
}

export const algorithmInfo: Record<string, AlgorithmInfo> = {
    'Bubble Sort': {
        name: 'Bubble Sort',
        description: 'Repeatedly compares adjacent elements and swaps them if out of order.',
        complexity: 'O(n²)',
        code: [
            'def bubble_sort(arr):',
            '    n = len(arr)',
            '    for i in range(n - 1):',
            '        for j in range(n - i - 1):',
            '            if arr[j] > arr[j + 1]:',
            '                arr[j], arr[j+1] = arr[j+1], arr[j]',
        ],
        eventLineMap: {
            compare: [4],
            swap: [5],
            range: [2],
        },
    },
    'Insertion Sort': {
        name: 'Insertion Sort',
        description: 'Builds a sorted section one element at a time by inserting each into its correct position.',
        complexity: 'O(n²)',
        code: [
            'def insertion_sort(arr):',
            '    for i in range(1, len(arr)):',
            '        key = arr[i]',
            '        j = i - 1',
            '        while j >= 0 and arr[j] > key:',
            '            arr[j + 1] = arr[j]',
            '            j -= 1',
            '        arr[j + 1] = key',
        ],
        eventLineMap: {
            compare: [4],
            read: [2],
            write: [5, 7],
            range: [1],
        },
    },
    'Selection Sort': {
        name: 'Selection Sort',
        description: 'Finds the minimum element and places it at the beginning, repeating for each position.',
        complexity: 'O(n²)',
        code: [
            'def selection_sort(arr):',
            '    for i in range(len(arr) - 1):',
            '        min_idx = i',
            '        for j in range(i + 1, len(arr)):',
            '            if arr[j] < arr[min_idx]:',
            '                min_idx = j',
            '        if min_idx != i:',
            '            arr[i], arr[min_idx] = arr[min_idx], arr[i]',
        ],
        eventLineMap: {
            compare: [4],
            swap: [7],
            range: [1],
        },
    },
    'Quick Sort': {
        name: 'Quick Sort',
        description: 'Picks a pivot, partitions elements around it, then recursively sorts each side.',
        complexity: 'O(n log n)',
        code: [
            'def quick_sort(arr, lo, hi):',
            '    if lo >= hi:',
            '        return',
            '    pivot = arr[hi]',
            '    i = lo - 1',
            '    for j in range(lo, hi):',
            '        if arr[j] < pivot:',
            '            i += 1',
            '            arr[i], arr[j] = arr[j], arr[i]',
            '    arr[i+1], arr[hi] = arr[hi], arr[i+1]',
            '    quick_sort(arr, lo, i)',
            '    quick_sort(arr, i + 2, hi)',
        ],
        eventLineMap: {
            pivot: [3],
            compare: [6],
            swap: [8, 9],
            partition: [0],
        },
    },
    'Merge Sort': {
        name: 'Merge Sort',
        description: 'Divides the array in half, sorts each half, then merges them back together.',
        complexity: 'O(n log n)',
        code: [
            'def merge_sort(arr, lo, hi):',
            '    if lo >= hi:',
            '        return',
            '    mid = (lo + hi) // 2',
            '    merge_sort(arr, lo, mid)',
            '    merge_sort(arr, mid + 1, hi)',
            '    merge(arr, lo, mid, hi)',
            '',
            'def merge(arr, lo, mid, hi):',
            '    aux = arr[lo:hi + 1]',
            '    i, j = 0, mid - lo + 1',
            '    for k in range(lo, hi + 1):',
            '        if aux[i] <= aux[j]:',
            '            arr[k] = aux[i]; i += 1',
            '        else:',
            '            arr[k] = aux[j]; j += 1',
        ],
        eventLineMap: {
            range: [3],
            merge: [6],
            compare: [12],
            write: [13, 15],
        },
    },
    'Heap Sort': {
        name: 'Heap Sort',
        description: 'Builds a max heap, then repeatedly extracts the maximum to sort the array.',
        complexity: 'O(n log n)',
        code: [
            'def heap_sort(arr):',
            '    n = len(arr)',
            '    for i in range(n // 2 - 1, -1, -1):',
            '        heapify(arr, n, i)',
            '    for i in range(n - 1, 0, -1):',
            '        arr[0], arr[i] = arr[i], arr[0]',
            '        heapify(arr, i, 0)',
            '',
            'def heapify(arr, size, i):',
            '    largest = i',
            '    left, right = 2*i + 1, 2*i + 2',
            '    if left < size and arr[left] > arr[largest]:',
            '        largest = left',
            '    if right < size and arr[right] > arr[largest]:',
            '        largest = right',
            '    if largest != i:',
            '        arr[i], arr[largest] = arr[largest], arr[i]',
            '        heapify(arr, size, largest)',
        ],
        eventLineMap: {
            compare: [11, 13],
            swap: [5, 16],
        },
    },
    'ADHD Sort': {
        name: 'ADHD Sort',
        description: 'Sorts a little, gets distracted, sorts more, gets distracted again...',
        complexity: 'O(n² + distractions)',
        code: [
            'function adhdSort(arr) {',
            '  let i = 0, sorted = 0',
            '  while (sorted < arr.length) {',
            '    for (let j = i+1; j < arr.length; j++)',
            '      if (arr[j] < arr[i]) swap(arr, i, j)',
            '    sorted++',
            '    if (Math.random() < 0.4)',
            '      swap(arr, rand(), rand())',
            '  }',
            '}',
        ],
        eventLineMap: {
            compare: [4],
            swap: [4, 7],
        },
    },
    'Anxiety Sort': {
        name: 'Anxiety Sort',
        description: 'Sorts it. Then checks again. And again. And again.',
        complexity: 'O(n² + paranoia)',
        code: [
            'function anxietySort(arr) {',
            '  arr.sort((a, b) => a - b) // done!',
            '  let checks = 0',
            '  while (checks < 20) {',
            '    for (let i = 0; i < arr.length - 1; i++)',
            '      if (arr[i] > arr[i+1]) throw "PANIC"',
            '    checks++ // ...but what if?',
            '  }',
            '}',
        ],
        eventLineMap: {
            write: [1],
            compare: [5],
        },
    },
    '6/7 Sort': {
        name: '6/7 Sort',
        description: 'Deletes everything except 6 and 7. Sorts what\'s left.',
        complexity: 'O(6/7)',
        code: [
            'function sixSevenSort(arr) {',
            '  for (let i = arr.length - 1; i >= 0; i--)',
            '    if (arr[i] !== 6 && arr[i] !== 7)',
            '      arr.splice(i, 1)',
            '  while (!sorted(arr))',
            '    swap(arr, 0, 1)',
            '}',
        ],
        eventLineMap: {
            read: [2],
            write: [3],
            compare: [4],
            swap: [5],
        },
    },
    'Freak Sort': {
        name: 'Freak Sort',
        description: 'Every swap is... intimate. It gets more intense as it goes.',
        complexity: 'O(n² × tension)',
        code: [
            'function freakSort(arr) {',
            '  for (let i = 0; i < arr.length; i++) {',
            '    for (let j = 0; j < arr.length - 1; j++) {',
            '      touch(arr[j], arr[j+1]) // oh',
            '      if (arr[j] > arr[j+1])',
            '        swap(arr, j, j+1) // ohhhh',
            '    }',
            '  }',
            '  finish(arr) // OHHHH',
            '}',
        ],
        eventLineMap: {
            read: [3],
            compare: [4],
            swap: [5],
        },
    },
    'Unsort': {
        name: 'Unsort',
        description: 'not sure what this is good for',
        complexity: 'O(n^2) backwards',
        code: [
            'function unsort(arr) {',
            '  if (isSorted(arr)) // why tho',
            '    return arr',
            '  for (let i = 0; i < arr.length; i++)',
            '    for (let j = i+1; j < arr.length; j++)',
            '      if (wouldCauseChaos(i, j))',
            '        swap(arr, i, j) // what is this good for',
            '  return arr // genuinely asking',
            '}',
        ],
        eventLineMap: {
            compare: [1, 5],
            swap: [6],
        },
    },
    'Uranium Sort': {
        name: 'Uranium Sort',
        description: 'one of the bars is radioactive. it\'s getting worse.',
        complexity: 'O(n² × half-life)',
        code: [
            'function uraniumSort(arr) {',
            '  let bar = arr[random()]',
            '  bar.radioactive = true',
            '  while (!sorted(arr)) {',
            '    for (let j = 0; j < arr.length - 1; j++) {',
            '      if (arr[j] > arr[j+1]) {',
            '        swap(arr, j, j+1)',
            '        if (touching(radioactive))',
            '          contaminate(arr[j]) // oh no',
            '      }',
            '    }',
            '  } // sorted. but at what cost.',
            '}',
        ],
        eventLineMap: {
            pivot: [2],
            compare: [5],
            swap: [6],
        },
    },
    'Bogo Sort': {
        name: 'Bogo Sort',
        description: 'Shuffles the entire array randomly. Checks if sorted. Repeats. Pray.',
        complexity: 'O((n+1)!) average',
        code: [
            'function bogoSort(arr) {',
            '  while (!isSorted(arr)) {',
            '    for (let i = arr.length - 1; i > 0; i--)',
            '      swap(arr, i, randInt(i + 1))',
            '  }',
            '  // still waiting...',
            '  // ...still waiting...',
            '  // heat death of universe',
            '}',
        ],
        eventLineMap: {
            compare: [1],
            swap: [3],
        },
    },
    'Stalin Sort': {
        name: 'Stalin Sort',
        description: 'Walks the array once. Any element out of order is eliminated. O(n). Problem solved.',
        complexity: 'O(n) — no appeals',
        code: [
            'function stalinSort(arr) {',
            '  let max = arr[0]',
            '  for (let i = 1; i < arr.length; i++) {',
            '    if (arr[i] >= max)',
            '      max = arr[i] // you may live',
            '    else',
            '      arr[i] = 0 // to the gulag',
            '  }',
            '  // arr is now "sorted"',
            '}',
        ],
        eventLineMap: {
            read: [1],
            range: [3],
            write: [6],
        },
    },
    'Thanos Sort': {
        name: 'Thanos Sort',
        description: 'Randomly eliminates half the array. Checks if sorted. Snaps again if not.',
        complexity: 'O(n × ∞ stones)',
        code: [
            'function thanosSort(arr) {',
            '  while (!isSorted(arr)) {',
            '    for (let i = 0; i < arr.length; i++)',
            '      if (Math.random() < 0.5)',
            '        arr[i] = 0 // *snap*',
            '    // perfectly balanced',
            '  }',
            '  // as all things should be',
            '}',
        ],
        eventLineMap: {
            compare: [1],
            pivot: [4],
            write: [4],
        },
    },
    'Communism Sort': {
        name: 'Communism Sort',
        description: 'Computes the average. Sets every element to the average. All bars are now equal.',
        complexity: 'O(n) — equality achieved',
        code: [
            'function communismSort(arr) {',
            '  let sum = 0',
            '  for (let v of arr)',
            '    sum += v // seize the means',
            '  let avg = sum / arr.length',
            '  for (let i = 0; i < arr.length; i++)',
            '    arr[i] = avg // redistribute',
            '  // everyone is equal now',
            '}',
        ],
        eventLineMap: {
            read: [3],
            write: [6],
        },
    },
    'Drunk Sort': {
        name: 'Drunk Sort',
        description: 'Like bubble sort, but 20% of the time it swaps things that were already correct.',
        complexity: 'O(n² × BAC)',
        code: [
            'function drunkSort(arr) {',
            '  for (let pass = 0; pass < n * 2; pass++)',
            '    for (let j = 0; j < arr.length - 1; j++)',
            '      if (Math.random() < 0.2)',
            '        swapIfOrdered(j, j+1) // oops',
            '      else',
            '        swapIfUnordered(j, j+1)',
            '  // *hiccup*',
            '}',
        ],
        eventLineMap: {
            compare: [2],
            swap: [4, 6],
        },
    },
    'Miracle Sort': {
        name: 'Miracle Sort',
        description: 'Checks if sorted. If not, checks again. Hopes for cosmic rays to flip the bits.',
        complexity: 'O(god willing)',
        code: [
            'function miracleSort(arr) {',
            '  let prayers = 0',
            '  while (!isSorted(arr)) {',
            '    // do absolutely nothing',
            '    // just believe harder',
            '    prayers++',
            '    if (prayers > 15)',
            '      panic_and_actually_sort(arr)',
            '  }',
            '}',
        ],
        eventLineMap: {
            compare: [2],
            swap: [7],
        },
    },
    'Sacrifice Sort': {
        name: 'Sacrifice Sort',
        description: 'Finds the tallest bar and sacrifices it to the void. Repeats until the array is humbled.',
        complexity: 'O(n² + blood)',
        code: [
            'function sacrificeSort(arr) {',
            '  for (let p = 0; p < n / 3; p++) {',
            '    let max = findMax(arr)',
            '    summonCircle(max)',
            '    arr[max] = 0 // the ritual',
            '  }',
            '  bubbleSort(arr) // clean up',
            '}',
        ],
        eventLineMap: {
            compare: [2],
            pivot: [3],
            write: [4],
            swap: [6],
        },
    },
    'Gravity Sort': {
        name: 'Gravity Sort',
        description: 'Drops every bar downward like gravity is pulling them. Heavy bars sink to the bottom.',
        complexity: 'O(n²) — 9.8 m/s²',
        code: [
            'function gravitySort(arr) {',
            '  for (let drop = 0; drop < n; drop++)',
            '    for (let i = n-1; i > 0; i--)',
            '      if (arr[i-1] > arr[i])',
            '        swap(arr, i-1, i) // *thud*',
            '  // everything settled',
            '}',
        ],
        eventLineMap: {
            compare: [3],
            swap: [4],
        },
    },
    'Procrastination Sort': {
        name: 'Procrastination Sort',
        description: 'Reads random elements. Compares random pairs. Wastes time. Panics and sorts at the last second.',
        complexity: 'O(n² + deadline)',
        code: [
            'function procrastinationSort(arr) {',
            '  for (let i = 0; i < n; i++) {',
            '    read(random()) // "research"',
            '    compare(random(), random()) // "planning"',
            '  }',
            '  // OH NO ITS DUE TOMORROW',
            '  insertionSort(arr) // panic mode',
            '}',
        ],
        eventLineMap: {
            read: [2],
            compare: [3],
            write: [6],
        },
    },
    'Paranoid Sort': {
        name: 'Paranoid Sort',
        description: 'Triple-checks every single comparison before committing to a swap. Just to be safe.',
        complexity: 'O(4n²) — trust issues',
        code: [
            'function paranoidSort(arr) {',
            '  for (let i = 0; i < n; i++)',
            '    for (let j = 0; j < n - i - 1; j++) {',
            '      compare(j, j+1) // first check',
            '      compare(j, j+1) // are you sure?',
            '      compare(j, j+1) // really sure?',
            '      if (arr[j] > arr[j+1]) // ok fine',
            '        swap(arr, j, j+1)',
            '    }',
            '}',
        ],
        eventLineMap: {
            compare: [3, 4, 5, 6],
            swap: [7],
        },
    },
    'Influencer Sort': {
        name: 'Influencer Sort',
        description: 'Only sorts the top 10% (the main characters). The rest? Not worth the engagement.',
        complexity: 'O(n × clout)',
        code: [
            'function influencerSort(arr) {',
            '  let topK = Math.floor(n * 0.1)',
            '  for (let i = 0; i < topK; i++) {',
            '    let max = findMax(arr, i)',
            '    swap(arr, i, max)',
            '    spotlight(i) // ✨ main character ✨',
            '  }',
            '  for (let i = topK; i < n; i++)',
            '    ignore(arr[i]) // irrelevant',
            '}',
        ],
        eventLineMap: {
            compare: [3],
            swap: [4],
            pivot: [5],
            read: [8],
        },
    },
    'Spaghetti Sort': {
        name: 'Spaghetti Sort',
        description: 'Compares elements at wildly varying distances. Like untangling spaghetti with a fork.',
        complexity: 'O(n^1.5) — al dente',
        code: [
            'function spaghettiSort(arr) {',
            '  let gap = Math.floor(n / 2)',
            '  while (gap > 0) {',
            '    for (let i = gap; i < n; i++)',
            '      for (let j = i; j >= gap; j -= gap)',
            '        if (arr[j-gap] > arr[j])',
            '          swap(arr, j-gap, j)',
            '        else break // untangled',
            '    gap = Math.floor(gap / 3)',
            '  } // *slurp*',
            '}',
        ],
        eventLineMap: {
            compare: [5],
            swap: [6],
        },
    },
    'Zombie Sort': {
        name: 'Zombie Sort',
        description: 'Sorts the array. But the sorted elements keep coming back from the dead and swapping around.',
        complexity: 'O(n² × undead)',
        code: [
            'function zombieSort(arr) {',
            '  for (let wave = 0; wave < 5; wave++) {',
            '    bubbleSort(arr) // phew, done',
            '    // ...wait',
            '    for (let r = 0; r < n * 0.15; r++) {',
            '      let a = rand(), b = rand()',
            '      resurrect(a, b) // BRAINS',
            '      swap(arr, a, b) // NOOO',
            '    }',
            '  }',
            '}',
        ],
        eventLineMap: {
            compare: [2],
            swap: [2, 7],
            pivot: [6],
        },
    },
    'Gaslighting Sort': {
        name: 'Gaslighting Sort',
        description: 'Sorts the array perfectly. Then quietly un-sorts a few elements. "It was always like that."',
        complexity: 'O(n² × denial)',
        code: [
            'function gaslightingSort(arr) {',
            '  for (let cycle = 0; cycle < 4; cycle++) {',
            '    bubbleSort(arr) // sorted!',
            '    // ...or is it?',
            '    let nudges = Math.floor(n * 0.1)',
            '    for (let r = 0; r < nudges; r++)',
            '      swap(arr, rand(), rand()+1)',
            '      // "I didn\'t touch anything"',
            '  }',
            '}',
        ],
        eventLineMap: {
            compare: [2],
            swap: [2, 6],
        },
    },
    'Optimist Sort': {
        name: 'Optimist Sort',
        description: 'Does one pass of bubble sort. Declares the array sorted. Leaves. Does not look back.',
        complexity: 'O(n) — good enough',
        code: [
            'function optimistSort(arr) {',
            '  for (let j = 0; j < arr.length - 1; j++)',
            '    if (arr[j] > arr[j+1])',
            '      swap(arr, j, j+1)',
            '  // looks sorted to me!',
            '  // narrator: it was not sorted.',
            '}',
        ],
        eventLineMap: {
            compare: [2],
            swap: [3],
        },
    },
};
